if (!require(shiny))
    install.packages('shiny')
# make sure you load DT *after* shiny
if (!require(DT))
    install.packages('DT')
if (!require(uuid))
    install.packages('uuid')
#if(!require(plotly))install.packages("plotly")
if (!require(shinyBS))
    install.packages('shinyBS')
if (!require(networkD3))
    install.packages('networkD3')
if (!require(shinyjs))
    install.packages('shinyjs')
if (!require(magrittr))
    install.packages('magrittr')
if (!require(devtools))
  install.packages('devtools')
if (!require(rcytoscapejs)) {
    library(devtools)
    devtools::install_github("cytoscape/r-cytoscape.js")
    if (!require(htmlwidgets))
        install.packages('htmlwidgets')
}
if (!require(MCL))
  install.packages('MCL')
if (!require(colourpicker))
  install.packages('colourpicker')
 
if (!require(VennDiagram)) 
install.packages("VennDiagram")
 
  
  library(BiocManager)
library(devtools)
library(rcytoscapejs)
library(shiny)
library(shinyBS)
library(DT)
library(uuid)
library(networkD3)
library(magrittr)
library(shinyjs)
#library(plotly)
library(MCL)
library(colourpicker)
library(BiocManager)
library(devtools)
library(rcytoscapejs)
library(shiny)
library(shinyBS)
library(DT)
library(igraph)
library(plyr)
library(d3Network)
library(uuid)
library(lattice)
# library(PerformanceAnalytics)
library(networkD3)
# library(plotly)
library(shinyjs)
library(Cairo)
library(randomcoloR)
library(MCL)
library(colourpicker)
library(VennDiagram)
library(visNetwork)


